kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "10.10.10.1" # default 127.0.0.1
  apiServerPort: 6443 # default random, must be different for each cluster
nodes:
- role: control-plane
- role: worker

