apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  boson-project.org: |
    selector:
      faas.domain: "boson-project.org"
  # Default is local only.
  svc.cluster.local: ""
