apiVersion: v1
kind: ConfigMap
metadata:
  name: config-network
  namespace: knative-serving
data:
  # If there exists an annotation `faas.subdomain` on the service,
  # use it instead of the default name.namespace
  domainTemplate: |-
    {{if index .Annotations "faas.subdomain" -}}
      {{- index .Annotations "faas.subdomain" -}}
    {{else -}}
      {{- .Name}}.{{.Namespace -}}
    {{end -}}
    .{{.Domain}}
