# Deploy artifacts for any pushes with a version tag (releases).
name: Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Test
        run:  make test
      - name: Build
        run:  make build
      - name: Image
        run:  make image
      - name: Push Image
        env:
          USER: ${{ secrets.QUAY_USERNAME }}
          PASS: ${{ secrets.QUAY_PASSWORD }}
        run: docker login -u "$USER" -p "$PASS" quay.io && make push
      - name: Compress Release Binary
        run: gzip ./faas
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./faas.gz
          asset_name: faas.gz
          asset_content_type: application/x-gzip

        # TODO:
        # - build cross-platform binaries (make release)
